### ISSUE TITLE
OC 1.5.10.22 Failed injecting component logic into class 

### ISSUE THREAD

**Issue by CaitlynMainer** [PC-Logix/OpenPrinter#22]
Reported on IRC
<Berserker2K3> [20:22:29] [Server thread/WARN]: Failed injecting component logic into class pcl.openprinter.tileentity.PrinterTE.
<Berserker2K3> java.lang.NullPointerException
<Berserker2K3>  at li.cil.oc.common.asm.ClassTransformer.isFinal(ClassTransformer.scala:368) ~[OpenComputers-MC1.7.10-1.5.10.22-universal.jar:?]
<Berserker2K3>  at li.cil.oc.common.asm.ClassTransformer.isAssignable(ClassTransformer.scala:360) ~[OpenComputers-MC1.7.10-1.5.10.22-universal.jar:?]
<Berserker2K3>  at li.cil.oc.common.asm.ClassTransformer$$anon$1.getCommonSuperClass(ClassTransformer.scala:396) ~[OpenComputers-MC1.7.10-1.5.10.22-universal.jar:?]

**Comment by CaitlynMainer** [comment]
fixed in dev build oc oc 1.5.12+ iirc
