### ISSUE TITLE
OpenPrinter-MC1.7.10-0.1.0.118

### ISSUE THREAD

**Issue by SvEgiiVEteR** [PC-Logix/OpenPrinter#25]
http://paste.ubuntu.com/11917192/
line 4131
java.lang.NullPointerException
    at net.minecraft.item.crafting.CraftingManager.func_92103_a(CraftingManager.java:230) ~[afe.class:?]
    at cpw.mods.fml.common.registry.GameRegistry.addShapedRecipe(GameRegistry.java:250) ~[GameRegistry.class:?]
    at cpw.mods.fml.common.registry.GameRegistry.addRecipe(GameRegistry.java:245) ~[GameRegistry.class:?]
    at pcl.openprinter.OpenPrinter.load(OpenPrinter.java:151) ~[OpenPrinter.class:?]

OpenPrinter-MC1.7.10-0.1.0.117
It works good

**Comment by CaitlynMainer** [comment]
This is probably because of the PR adding oredict support for crafting, I'll look at this in a bit
I've hidden the upload so no one else will get it.

**Comment by CaitlynMainer** [comment]
I've hidden the upload so no one else will get it.

**Comment by Kubuxu** [comment]
Shiet, it was suppose to work.

**Comment by marcin212** [comment]
@Kubuxu, You forgot add `new ShapedOreRecipe(` in line [#L151](https://github.com/PC-Logix/OpenPrinter/blob/8888bcf64648b1b7969463089b4b26da0f1b0e90/src/main/java/pcl/openprinter/OpenPrinter.java#L151) and [#L156](https://github.com/PC-Logix/OpenPrinter/blob/8888bcf64648b1b7969463089b4b26da0f1b0e90/src/main/java/pcl/openprinter/OpenPrinter.java#L156)

**Comment by Kubuxu** [comment]
See #26

**Comment by CaitlynMainer** [comment]
119 is building with this fix, will be on Curse as soon as they approve it.

**Comment by CaitlynMainer** [comment]
Build 119 is approved.
