### ISSUE TITLE
ArrayIndexOutOfBoundsException when opening paper.

### ISSUE THREAD

**Issue by slendidev** [PC-Logix/OpenPrinter#53]
I print some stuff, then i open it up and i get a crash. This is what it says:
> Time: 4/19/20 4:33 AM
> Description: Rendering screen
> 
> java.lang.ArrayIndexOutOfBoundsException: 2
> 	at pcl.openprinter.gui.PaperGUI.func_73863_a(PaperGUI.java:116)
> 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
> 	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
> 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1457)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Please fix this and make a new release in the releases tab. Urgent!

**Comment by ben-mkiv** [comment]
hi, i can't reproduce the issue, could you please share your lua script?

**Comment by slendidev** [comment]
I can't since the data is corrupted :/

**Comment by ben-mkiv** [comment]
which data? your player instance? if so you can upload the player.dat file and i'll fix it for you or you can use any NBT Editor and remove the broken item from the player inventory

**Comment by slendidev** [comment]
data i mean computer files. they're gone
